### ISSUE TITLE
dqn

### ISSUE THREAD

**Issue by ycc234** [nubot-nudt/dynamic_task_allocation#12]
你好，用DQN训练的时候会出现只有一个机器人走了一步，就不再动了，请问是什么问题

**Comment by ycc234** [comment]
['Traceback (most recent call last):\n', '  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 625, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "train.py", line 73, in get_action_callback\n    action = DQN.choose_action(observation, task_status)\n', "NameError: name 'DQN' is not defined\n"]
[ERROR] [1659856278.818122]: Error processing request: name 'DQN' is not defined
显示这个错误，可以帮忙看一下吗，谢谢
